version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 0
      ZOO_SERVERS: server.0=zoo1:2888:3888 server.1=zoo2:2888:3888 server.2=zoo3:2888:3888

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.0=zoo1:2888:3888 server.1=zoo2:2888:3888 server.2=zoo3:2888:3888

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.0=zoo1:2888:3888 server.1=zoo2:2888:3888 server.2=zoo3:2888:3888
