---

openapi: 3.1.0

paths:
  /hoge:
    get:
      parameters:
        - in: header
          name: X-Request-ID
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: ok
          content:
            'application/json':
              schema:
                required:
                  - color
                type: object
                properties:
                  color:
                    type: string
                additionalProperties: false

info:
  title: Test
  version: 1.0.0
